# Welcome to Jekyll!
# Site settings
title: "1000 malých radostí"
description: ""
baseurl: ""
url: "http://alixedi.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "o nás"
    url: /about
  - title: "náš cieľ"
    url: http://twitter.com/alixedi
  - title: "TOP10"
    url: http://github.com/alixedi
  - title: "kontakty"
    url: /feed.xml